apiVersion: hydra.microsoft.com/v1
kind: Component
metadata:
  name: another-component
spec:
  name: another-component
  workloadType: core.hydra.io/v1alpha1.Singleton
  os: linux
  containers:
    - name: foo
      image: nginx:latest
