
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "scylla.fullname" . }}
  labels:
{{ include "scylla.labels" . | indent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "scylla.fullname" . }}
  labels:
{{ include "scylla.labels" . | indent 4 }}
rules:
- apiGroups: ["", "apps", "batch", "extensions", "core.hydra.io"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "scylla.fullname" . }}
  labels:
{{ include "scylla.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "scylla.fullname" . }}
  namespace: "default"  # FIXME
roleRef:
  kind: Role
  name: {{ template "scylla.fullname" . }}