# This is a single-shot configuration that creates the entire Docker Voting app
# all in one go.
apiVersion: core.hydra.io/v1alpha1
kind: ApplicationConfiguration
metadata:
  name: voter-app
spec:
  components:
    - name: postgres
      instanceName: voter-pg
    - name: redis
      instanceName: voter-redis
    - name: voting-worker
      instanceName: voter-worker
    - name: voting-frontend
      instanceName: voter-fe
      traits:
      - name: ingress
        parameterValues:
        - name: hostname
          value: voting.example.com
        - name: path
          value: /
    - name: voting-admin
      instanceName: voter-admin
      traits:
      - name: ingress
        parameterValues:
        - name: hostname
          value: admin.example.com
        - name: path
          value: /