# This is a single-shot configuration that creates the entire Docker Voting app
# all in one go.
apiVersion: core.hydra.io/v1alpha1
kind: Configuration
metadata:
  name: voter-app
spec:
  components:
    - name: postgres
    - name: redis
    - name: voting-worker
    - name: voting-frontend
      traits:
      - name: ingress
        parameterValues:
        - name: hostname
          value: voting.example.com
        - name: path
          value: /
    - name: voting-admin
      traits:
      - name: ingress
        parameterValues:
        - name: hostname
          value: admin.example.com
        - name: path
          value: /